# GitBook 配置文件
# 用于 GitBook.com 平台的配置

root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

format:
  page:
    insertAnchors: true
    editLink: true
    lastModified: true

pdf:
  fontSize: 12
  paperSize: a4
  margin:
    top: 56
    bottom: 56
    right: 62
    left: 62
